### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by IzzySoft** [jetspiking/AndME#1]
First thanks for making your app available as FOSS and even providing the APK for end users! Could you please make sure the versioning is unique? Currently, both APKs (v0.0.1 and v 1.0.0) identify as

    package: name='com.dustinhendriks.andme' versionCode='2' versionName='Alpha'

* `versionCode` is what Android uses to tell versions apart. This is an integer that must be increased with each release so the new version is presented to the user as update.
* `versionName` is for humans to read. [Semantic versioning](https://semver.org/) is a good idea, and you're already using that for tags. I'd recommend using the same for `versionName` – so the currently latest version would identify as

        package: name='com.dustinhendriks.andme' versionCode='2' versionName='1.0.0'

(though as the previous one already used `versionCode: 2`, that should rather have been 3). The place to adjust that is [here](https://github.com/jetspiking/AndME/blob/main/AndME/app/build.gradle#L9) (plus the current line 13). If you could follow that pattern starting with the next release, that would be much appreciated. Thanks in advance!

**Comment by jetspiking** [comment]
Thank you for the feedback and your time to open this issue @IzzySoft. For potential upcoming versions I will adjust the version information.

**Comment by IzzySoft** [comment]
Great, thanks! Be welcome to give me a ping when the next version is there and I'll gladly cross-check, so this issue can be solved/closed then.

**Comment by IzzySoft** [comment]
Hmpf, as the current naming confuses my updater (it downloads the same version over and over as it cannot match the tag name), I'll have to disable auto-updates for now. Please make sure to give me a ping when a fixed release is available. Thanks!

**Comment by IzzySoft** [comment]
> For potential upcoming versions I will adjust the version information.

```gradle
        versionCode 2

        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        versionName = 'Alpha'
```

[`versionName`](https://github.com/jetspiking/AndME/blob/main/AndME/app/build.gradle#L13) is still set to "Alpha". This might also be an issue for #3 (and F-Droid's update checker). Any ETA for a fixed release?

**Comment by jetspiking** [comment]
Hi @IzzySoft, At the moment I don't have any new features or work done to the app. If required I could make a commit purely to fix the versioning. But nothing planned at the moment.

**Comment by IzzySoft** [comment]
Then maybe just keep it on your todo list (e.g. by keeping this issue open for now) and please remember adjusting it with the next release. Thanks!

**Comment by IzzySoft** [comment]
Now there's an [RFP](https://gitlab.com/fdroid/rfp/-/issues/2344) opened at F-Droid, so expect more upcoming questions. Like, the tag name says `1.0.0` which doesn't meet either `versionName` or `versionCode`, so we cannot even try for reproducible builds (to publish the APK you've built if it's binary-identical to our build) as we have no pattern to match the URL :man_shrugging:

So what do you think: First wait if that condition is met (once we've checked manually) – to see what other things might come up? I've just linked from that RFP to the issue here and vice-versa for communication in this context. Scan report looks fine there, so if something else is to come up that would be once the merge request was opened.

**Comment by jetspiking** [comment]
@IzzySoft I think I'll create a new release tomorrow to set `versionName` and `versionCode` to `2.0.0`. Otherwise I'll keep postponing this issue. Other issues can be fixed at a later time then, I think.

**Comment by IzzySoft** [comment]
You cannot set `versionCode` to `2.0.0`, that must be an integer :wink: But apart from that: thanks! If the tag name then reflects `versionName` (i.e. is `2.0.0` or `v2.0.0` – it must include `versionName` or `versionCode`), all should be fine.

**Comment by jetspiking** [comment]
Hi @IzzySoft,

The new release is published. You can find it here:
https://github.com/jetspiking/AndME/releases

**Comment by IzzySoft** [comment]
Thanks! That enabled me to activate auto-updates in my repo as well. But as you did not increase `versionCode`, 2.0.0 simply overwrote the APK of 1.0.0 (F-Droid would instead have rejected the update as "oh, we have that already" – so please remember to increase it with future releases :wink:).

**Comment by jetspiking** [comment]
Hey @IzzySoft, I found a bug that occured in the new version. I fixed it and incremented the `versionCode` to 3 and set `versionName` to `2.0.1`.

**Comment by IzzySoft** [comment]
Looks like you were lucky enough to have the APK attached just seconds before my updater looked for it :partying_face: It went live just half an hour later. And did not throw a warning, so all fine :smiley: Thanks!
