### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [jetspiking/AndME#14]
Great to see there are new releases! Since the last ones in 2023, my scanner has been updated as well – and now points out on the current one:

```
! repo/com.dustinhendriks.andme_5.apk declares sensitive permission(s):
  android.permission.QUERY_ALL_PACKAGES android.permission.READ_EXTERNAL_STORAGE
  android.permission.MANAGE_EXTERNAL_STORAGE
! repo/com.dustinhendriks.andme_5.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

While `QUERY_ALL_PACKAGES` is clear (for the app list to pick from), could you please outline what those storage permissions are needed for? As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

**Comment by IzzySoft** [comment]
PS, getting further down in my report I see an even bigger issue, keeping AndMe from being updated:

```
2024-06-01 03:34:26,546 WARNING: "com.dustinhendriks.andme_5.apk" is signed by a key that is not allowed:
fb73fad3ca80861c44a5e993ce1314dbe020866b7a82be7387f0580e771ddc8b
```

What happened to your signing key if I may ask? This is the current one:

```
Signer #1 certificate DN: C=NL, O=Open System Query, CN=Dustin Hendriks
Signer #1 certificate SHA-256 digest: fb73fad3ca80861c44a5e993ce1314dbe020866b7a82be7387f0580e771ddc8b
Signer #1 certificate SHA-1 digest: ddc5c6702b8e2625ad71e9824b2e48f2ed9ae05e
Signer #1 certificate MD5 digest: 17bd51dffcd4a7dfaeeae0416712ddf2
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

Up to the latest release with `versionCode:4` (btw, `versionCode` needs to be increased with each release; it seems like `5` has been re-used a few times) it was

```
Signer #1 certificate DN: CN=Dustin Hendriks, OU=Dustin Hendriks, O=Dustin Hendriks
Signer #1 certificate SHA-256 digest: 1095f11673944de3df5493d4695afee4051e879a893026a2edcda56afee10eb8
Signer #1 certificate SHA-1 digest: d144a764a0503a996b85e6c29830a96cf323d8c0
Signer #1 certificate MD5 digest: 694c81551935ac5176b3619fa25639bb
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

As the key differs, Android refuses to update (and so does my repo, as signing keys are pinned there).

**Comment by jetspiking** [comment]
QUERY_ALL_PACKAGES allows the app built with to check the installed app inventory of the device with Android 11 and higher. The app can query all installed app lists from the smartphone.

I can add this to the manifest:
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}

And update the corresponding version number.

Unfortunately, I lost my old signing key, so I created a new one on my Linux development machine. Can the key be updated or adjusted somehow?

**Comment by IzzySoft** [comment]
> QUERY_ALL_PACKAGES allows the app built with to check the installed app inventory

Yeah, as pointed out: **that** one is clear. It's the other two which are not: `MANAGE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE`.

> I can add this to the manifest:

That'd be great, thanks! Just note it doesn't go to the manifest but to your [`build.gradle`](https://github.com/jetspiking/AndME/blob/main/AndME/app/build.gradle). The `android` block is already there (starting on line 3), so you'd just need to inject the `dependenciesInfo` part into it. For the IzzyOnDroid repo, the `includeInApk = false` is the important setting. If you think you need that blob for PlayStore, simply omit the `includeInBundle = false` part there.

> Unfortunately, I lost my old signing key, so I created a new one on my Linux development machine. Can the key be updated or adjusted somehow?

That can be done of course. But as this is a security matter, some verification is needed. You can find some measures and the related background here: [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss) Summing up the usual measures:

* you didn't sign your commits, so we cannot check that way. Please consider starting signing them now (as well as making backups of your current key).
* is there a confirmed different means of contact? Unfortunately, Gmail might cause issues as they often do not deal nice with smaller mail providers. You've specified a Gmail address with your metadata, so maybe that can be used for a "weak verification" ("weak" as it's possible you're using that account for sign-in to Github, so if someone compromised your mail address both would be compromised. Unfortunately Github does not show if 2FA is enabled for your account).
* There's no person established who could vouch for you (i.e. someone we both trust, and who can confirm having checked on a "secure channel"). If you can think of someone, can't hurt to set this up.

Also see "Lesson number 3" in the linked document. Changing the signing key makes it impossible to update the app: one has to uninstall and re-install. So you should at least mention the fact in the release notes so people know it's intended and what they'll have to do.

**Comment by jetspiking** [comment]
`MANAGE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` are used to gain access to read the system wallpaper. Without this, the application is unable to display a background wallpaper selected in Android.

Unfortunately, as I work solo, there isn't a trusted person who can vouch for me through a secure channel at this time. I do have an alternative second mail address not related to GitHub that could be used for verification purposes. Do you want me to share this, and how do you want me to share this?

In the future, I will make sure to backup the signing key properly. Steps for a new release would be:
- Increment version number
- Add manifest `dependenciesInfo` you shared
- Describe that new signing key was generated in the release notes due to losing the "old" one

At the moment, due to limited time available, I would prefer not signing commits and abstaining from adding complexity to my workflow. However, please consider I do use 2FA and use personal access tokens that expire within a couple of days.

**Comment by IzzySoft** [comment]
> are used to gain access to read the system wallpaper

Thanks! Updated here.

> alternative second mail address

Too late now (in case your repo would have been compromised, how should I know it's really you? Idea of confirmation is to establish the fact it's really you), but might be a good idea for the future. Did you receive the mail I've sent you?

> In the future

:+1:

> Describe that new signing key was generated in the release notes due to losing the "old" one

Note you can also use fastlane's per-release changelogs for that, which with most clients are displayed right next to the app description.

> 2FA and use personal access tokens

Very good, thanks! Just waiting for your reply on my mail then.

Btw: Signing commits is easy to set up and, once set up, does not take noticeably longer than unsigned commits (just the time you need to enter your passphrase). If you cannot do this due to automation, you could consider it at least for tags/releases maybe, as a first step. Not mandatory, just a hint to what could possibly be done :wink:

**Comment by jetspiking** [comment]
> Too late now (in case your repo would have been compromised, how should I know it's really you? Idea of confirmation is to establish the fact it's really you), but might be a good idea for the future. Did you receive the mail I've sent you?

I received your mail. I send a reply a few minutes ago. I will send an alternative communication method to you as well later, so you can always verify over that method whether it is me.

> Note you can also use fastlane's per-release changelogs for that, which with most clients are displayed right next to the app description.

I will look into this, thank you for the suggestion!

**Comment by IzzySoft** [comment]
Thanks! Enabled everything again, pulled the APK, and set up a per-release changelog for this version manually, pointing out the need to uninstall/reinstall the app in order to update. Old key will be disabled in a month, and the related APKs removed.

All done here then, so let's close the issue. Should any questions have remained on your end, simply give me a ping. Thanks for your support!

**Comment by jetspiking** [comment]
@IzzySoft Awesome, thank you for the assistance! I made a backup of the signing key, so it won´t happen again :).
