### ISSUE TITLE
Thanks for AndME :)

### ISSUE THREAD

**Issue by mediaexplorer74** [jetspiking/AndME#2]
Super-cool theme. You're great developer. I noticed the code constructed with Java, not C#. SO crazy thing! Amazing work, really.
You're polyglot. =)

Best wishes,
Andrey aka M.E.
Apologet of "Project Jemini" (Jemini, in Zodiac mythology, is/are similar to Goo. Android Material Design+ WP Metro styles ;)))

**Comment by jetspiking** [comment]
Hi Andrey,

Thank you for your kind words! I really appreciate it. I contacted you by e-mail btw (the one on your GitHub), because I noticed you are very active in the Windows Phone community. 

Nice to meet you anyways :)

Kind regards,
Dustin
