### ISSUE TITLE
Support landscape mode

### ISSUE THREAD

**Issue by xmha97** [jetspiking/AndME#8]
Please add support landscape mode.

**Comment by xmha97** [comment]
This feature can be suitable for tablets:

![69452edc-d254-4489-a10d-b77c1c777dfe_1.a57878498d7b840db27560088bc69d5a.jpg](https://user-images.githubusercontent.com/23485114/216810233-17caeaf2-8cf2-4850-aafe-c3bd4e8f6845.jpg)

**Comment by jetspiking** [comment]
Still thinking about how I could implement this. I might just update all the icons and labels to simply display rotated 90 degrees without any additional changes on the layout.

**Comment by xmha97** [comment]
It's very good 👍

**Comment by jetspiking** [comment]
@xmha97 Support for landscape mode is implemented!
